services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stock_manager
    restart: unless-stopped
    ports:
      - "81:80" # I am on ubuntu, to avoid to stop my local apache service, better to set another port
      - "443:443"
    depends_on:
      - mysql
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: stock
      MYSQL_USER: stockAdmin
      MYSQL_PASSWORD: passwordAdmin
    ports:
      - "3307:3306" # to avoid problems if someone has mysql locally installed
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge